### ISSUE TITLE
Configuration files

### ISSUE THREAD

**Issue by gchp** [gchp/iota#51]
It would be great to have some kind of simple configuration file which users could use to tweak Iota behaviour. Things like using spaces or tabs, tab width, and so on.

Rust projects seem to use toml a lot for configuration files. Perhaps this would be a good starting place?

``` toml
[config]
spaces = true
tabwidth = 4
```

or similar?

In the future there will be a proper plugin system, but we need something simple to start with.

**Comment by torwart** [comment]
Also **YAML** would be cool! I currently also work on an Editor (inC++/wxWidgets) and I have fall in love with **YAML**, then it will looks like this:

```yaml
# iota configuration
spaces: true
tabwidth: 4
recent_file: /example.txt
```

And there [are](https://github.com/Stibbons/rust-yaml) [two](https://github.com/kimhyunkang/libyaml-rust) good parsers out in the wild.
